function psi = psi_1AFC_setup(stim_range)
% psi_1AFC_setup(stim_range) provides an access to the settings
% of the threshold estimation procedure psi_1AFC.m
% 
% It creates a structure "psi" with all relevant settings that can be
% later on easily modified, e.g. "psi.trials_psi = 50;"
%
% % Input %
%   stim_range            - range of possible stimulus intensities
%
%
% % Settings %
%
%   % General
%   psi.rng_state         - state of random number generator (not mandatory)
%   psi.file_prefix       - prefix for saving files (e.g., analog input recording)
%
%   % Up/down method
%   psi.UD_up             - number of misses to increase intensity
%   psi.UD_down           - number of hits to decrease intensity
%   psi.UD_stepSizeUp     - intensity step up
%   psi.UD_stepSizeDown   - intensity step down
%   psi.UD_stopCriterion  - 'trials' or 'reversals'
%   psi.UD_stopRule       - number of <stopCriterion>
%   psi.UD_startValue     - first intensity
%   psi.UD_xMax           - maximum intensity
%   psi.UD_xMin           - minimum intensity
%
%   psi.UD_meanNumber     - number of <stopCriterion> for mean analysis
%
%   For details: doc PAL_AMUD_setupUD
%                doc PAL_AMUD_analyzeUD
%
%
%   % Psi method settings
%   psi.trials_psi        - trial number with psi method intensity
%   psi.PF                - Psychometric function assumed by Psi method
%	psi.stim_range        - considered stimulus intensities
%
%   %% Priors considered for posterior distribution
%   psi.priorAlphaRange   - not available, defined by up/down method results
%   psi.priorBetaRange    - slope vector
%   psi.priorGammaRange   - guess rate vector/scalar
%   psi.priorLambdaRange  - lapse rate vector/scalar
%
%   psi.priorAlphaSteps   - step size for prior alpha range
%	psi.UD_range_factor	  - factors for up/down mean range (min/max) that set prior alpha range
%
%   For details: doc PAL_AMPM_setupPM
%
%
%   % Procedure
%   psi.psi_null_rate - ratio of trials w/o stimulation (psi method)
%	psi.near_p      - performance level for near-threshold intensity (e.g., 0.40)
%   psi.supra_p 	- performance level for supra-threshold intensity (e.g., 0.90)
%	psi.trials_test - trial numbers for each "intensity" in psi.stim_test
%   psi.stim_test   - performance levels for test intensities (> guess & < lapse rate)
%
%
%   % Stimulus
%   psi.pulse_t     - duration of stimuls (rectangular pulse) in ms
%   psi.wave_t      - duration of waveform with rectangular pulse in ms
%   psi.stim_dec    - decimal position test intensities are rounded to
%
%
%   % Trial design
%   psi.fix_t       - duration of fixation cross in s
%   psi.cue_t       - duration of stimulus cue in s
%   psi.stim_delay  - min/max vector for pseudo-randomized stimulus delay in s
%   psi.resp_window - 'variable'/'fixed' = stop or continue after first button press
%   psi.maxRespTime - maximum response time in s
%   psi.ITI         - min/max vector of pseudo-randomized inter trial interval (ITI) in s
% 
%
%   % Screen design
%   psi.window_color- screen background rgb color vector
%
%   %% Text
%   psi.txt_color   - text rgb color vector
%   psi.txt_font    - font type
%   psi.txt_size    - font size for response screen
%   psi.cue_size    - font size for fix, cue and pause screens
%
%   %% Messages
%   psi.fix         - fixation symbol (e.g., '+')
%   psi.cue         - cue symbol (e.g., '~+~')
%   psi.pause       - pause symbol (e.g., '-')
%   psi.resp_txt    - response options, yes-no-order important, e.g. ['J'; 'N']
%   psi.resp1_offset- 1st response text offset left from screen center 
%
%   % Buttons
%   psi.lpt_adr     - parallel port address (see device manager - LPT1 details - resources)
%   psi.lpt_dir     - parallel port direction ('bi' or 'uni')
%   psi.btn         - button codes for response options
%   psi.btn_esc     - button code for quiting experiment
%
%   %% Instruction
%   psi.instr_dir   		  - instruction directory with condition subdirectories
%                     			(relative to directory of psi_1AFC.m)
%   psi.instr_subdir_wildcard - instruction subdirectory wildcard
%   psi.instr_img_wildcard    - filename wildcard of instruction image files
%
%    
% Author:           Martin Grund
% Last update:      January 26, 2016

%% Settings

%% General
% psi.rng_state = sum(100*clock); % If not defined, generated by psi_1AFC.
psi.file_prefix = 'psi_1AFC_';

%% Up/down method settings
psi.UD_up = 1;
psi.UD_down = 3;
psi.UD_stepSizeUp = 0.2;
psi.UD_stepSizeDown = 0.2;
psi.UD_stopCriterion = 'trials';
psi.UD_stopRule = 25;
psi.UD_startValue = mean(stim_range);
psi.UD_xMin = min(stim_range);
psi.UD_xMax = max(stim_range);
psi.UD_meanNumber = 10;

%% Psi method settings
psi.trials_psi = 25;
psi.PF = @PAL_Quick;
psi.stim_range = stim_range;
psi.priorBetaRange = 0.3:.1:1.5;
psi.priorGammaRange = .03;
psi.priorLambdaRange = .03;

psi.priorAlphaSteps = .05;
psi.UD_range_factor = [.85; 1.15];

%% Procedure
psi.psi_null_rate = 0; % percentage of total trials in psi block -> psi.trials_psi ~ (1 - psi.null_rate)

psi.near_p = .45;
psi.supra_p = .95; % < maximum lapse rate (max(psi.priorLambdaRange))

psi.trials_test = [5; 10; 5;];
psi.stim_test = [0; psi.near_p; psi.supra_p;]; % performance levels > guess & < lapse rate

%% Stimulus
psi.pulse_t = 0.2; % ms
psi.wave_t = 10; % ms
psi.stim_dec = 2;

%% Trial design
psi.fix_t = 1.000;
psi.cue_t = 1.000;
psi.stim_delay = [0.885 0.885];
psi.resp_window = 'variable';
psi.maxRespTime = 4.000;
psi.ITI = [0.500 0.500];

%% Screen design
psi.window_color = [200 200 200]; %[250 250 250]; % grey98 (very light grey)

%% Text
psi.txt_color = [40 40 40]; % grey15-16 (anthracite)
psi.txt_font = 'Arial';
psi.txt_size = 30;
psi.cue_size = 50;

%% Messages
psi.fix = '+';
psi.cue = '~+~';
psi.pause = '+';
psi.resp_txt = ['J'; 'N'];
psi.resp1_offset = 75;

%% Buttons
psi.lpt_adr = '378';
psi.lpt_dir = 'bi';
psi.btn = [6 7];
psi.btn_esc = 1;

%% Instruction
psi.instr_dir = '/instr/';
psi.instr_subdir_wildcard = 'condition_*';
psi.instr_img_wildcard = 'instruction.*.png';